on:
  workflow_dispatch:
  release:
    types: [published]
    secrets:
      VIAM_CLI_AUTH:
        required: true

jobs:
  module-upload:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v3

    - name: Check out RDK
      uses: actions/checkout@v3
      with:
        repository: viamrobotics/rdk
        path: ./rdk
        ref: refs/heads/main

    - name: Download release tarball
      uses: robinraju/release-downloader@v1.8
      with:
        tag: ${{ github.event.release.tag_name }}
        tarBall: true

    - name: Set CLI Auth
      run: |
        mkdir -p ~/.viam
        echo ${{ secrets.VIAM_CLI_AUTH }} | base64 -d > ~/.viam/cached_cli_config.json
  
    - name: Module Upload for linux/arm64
      run: go run ./rdk/cli/viam/main.go --base-url='https://app.viam.dev:443' module upload --platform "linux/arm64" --version ${{github.event.release.tag_name}} ../../viam-modular-resources-${{github.event.release.tag_name}}.tar.gz